
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ADD ALTER AND AS AVG COMMA COUNT DELETE DROP EQ FROM GT LP LT MAX MIN NAME NUMBER OR RP SELECT SUM TABLE WHEREquery : delete\n             | select\n             | alter_table\n             | drop_tabledelete : DELETE FROM NAME WHERE condition\n              | DELETE FROM NAMEselect : SELECT NAME FROM NAME WHERE condition\n              | SELECT NAME FROM NAMEalter_table : ALTER TABLE NAME ADD NAME NAMEdrop_table : DROP TABLE NAMEcondition : NAME EQ NUMBER\n                 | NAME LT NUMBER\n                 | NAME GT NUMBER\n                 | condition AND condition\n                 | condition OR conditionagg : COUNT LP NAME RP\n           | SUM LP NAME RP\n           | AVG LP NAME RP\n           | MIN LP NAME RP\n           | MAX LP NAME RP'
    
_lr_action_items = {'DELETE':([0,],[6,]),'SELECT':([0,],[7,]),'ALTER':([0,],[8,]),'DROP':([0,],[9,]),'$end':([1,2,3,4,5,14,17,19,22,30,31,32,33,34,35,36,],[0,-1,-2,-3,-4,-6,-10,-8,-5,-7,-9,-11,-12,-13,-14,-15,]),'FROM':([6,11,],[10,15,]),'NAME':([7,10,12,13,15,18,20,23,24,28,29,],[11,14,16,17,19,21,24,21,31,21,21,]),'TABLE':([8,9,],[12,13,]),'WHERE':([14,19,],[18,23,]),'ADD':([16,],[20,]),'EQ':([21,],[25,]),'LT':([21,],[26,]),'GT':([21,],[27,]),'AND':([22,30,32,33,34,35,36,],[28,28,-11,-12,-13,28,28,]),'OR':([22,30,32,33,34,35,36,],[29,29,-11,-12,-13,29,29,]),'NUMBER':([25,26,27,],[32,33,34,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'query':([0,],[1,]),'delete':([0,],[2,]),'select':([0,],[3,]),'alter_table':([0,],[4,]),'drop_table':([0,],[5,]),'condition':([18,23,28,29,],[22,30,35,36,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> query","S'",1,None,None,None),
  ('query -> delete','query',1,'p_query','newParser.py',92),
  ('query -> select','query',1,'p_query','newParser.py',93),
  ('query -> alter_table','query',1,'p_query','newParser.py',94),
  ('query -> drop_table','query',1,'p_query','newParser.py',95),
  ('delete -> DELETE FROM NAME WHERE condition','delete',5,'p_delete','newParser.py',99),
  ('delete -> DELETE FROM NAME','delete',3,'p_delete','newParser.py',100),
  ('select -> SELECT NAME FROM NAME WHERE condition','select',6,'p_select','newParser.py',110),
  ('select -> SELECT NAME FROM NAME','select',4,'p_select','newParser.py',111),
  ('alter_table -> ALTER TABLE NAME ADD NAME NAME','alter_table',6,'p_alter_table','newParser.py',122),
  ('drop_table -> DROP TABLE NAME','drop_table',3,'p_drop_table','newParser.py',132),
  ('condition -> NAME EQ NUMBER','condition',3,'p_condition','newParser.py',139),
  ('condition -> NAME LT NUMBER','condition',3,'p_condition','newParser.py',140),
  ('condition -> NAME GT NUMBER','condition',3,'p_condition','newParser.py',141),
  ('condition -> condition AND condition','condition',3,'p_condition','newParser.py',142),
  ('condition -> condition OR condition','condition',3,'p_condition','newParser.py',143),
  ('agg -> COUNT LP NAME RP','agg',4,'p_agg','newParser.py',158),
  ('agg -> SUM LP NAME RP','agg',4,'p_agg','newParser.py',159),
  ('agg -> AVG LP NAME RP','agg',4,'p_agg','newParser.py',160),
  ('agg -> MIN LP NAME RP','agg',4,'p_agg','newParser.py',161),
  ('agg -> MAX LP NAME RP','agg',4,'p_agg','newParser.py',162),
]
